from llm.llmSetUp import LLM
from rag.retriever import retriever

def search_code(state):
    """
    Search source code, APIs, functions, classes,
    and implementation logic.

    Use for:
    - debugging
    - architecture
    - implementation tracing
    - business logic analysis
    """

    result = retriever(state["user_query"], state["doc_type"])

    return {**state, "retrieved_data": result, "tool_outputs": {

        **state.get("tool_outputs", {}),

        "search_code": result
    }}


def search_records(state):
    """
    Search logs, runtime events, failures,
    incidents, and monitoring records.

    Use for:
    - production debugging
    - outages
    - crashes
    - latency investigations
    """

    result = retriever(state["user_query"], state["doc_type"])

    return {**state, "retrieved_data": result, "tool_outputs": {

        **state.get("tool_outputs", {}),

        "search_code": result
    }}


def search_docs(state):
    """
    Search documentation, guides, setup instructions,
    policies, architecture docs, and onboarding material.

    Use for:
    - setup help
    - project explanation
    - technical documentation
    - workflows
    """

    result = retriever(state["user_query"], state["doc_type"])

    return {**state, "retrieved_data": result, "tool_outputs": {

        **state.get("tool_outputs", {}),

        "search_code": result
    }}


def summarize(state):
    """
    Generate a concise answer by summarizing retrieved content in response to a user query.

    This function uses an LLM to synthesize information from provided context (`content`)
    and produce an answer strictly grounded in that data.

    Parameters:
    ----------
    query : str
        The user's question or information need.

    content : list or str
        Retrieved data to summarize. Typically a list of dictionaries containing
        "content" (text/code) and optional metadata, or a pre-formatted string.

    Returns:
    -------
    str
        A concise, context-grounded answer generated by the LLM.

    Behavior:
    --------
    - Uses only the provided content to generate the answer.
    - Avoids hallucination by restricting output to given data.
    - Returns a fallback response if insufficient information is available.

    Notes:
    ------
    - The quality of the output depends heavily on the quality and relevance
      of the retrieved content.
    - Content should ideally be pre-cleaned and structured before being passed in.
    """

    llm = LLM()

    prompt = f"""
    You are an summarizer

    Use ONLY the provided with data to generate summary of it and answer the users query.

    Query:
    {state["user_query"]}
    
    RULES:
    - Do not hallucinate
    - Be concise
    - If insufficient info exists, say so

    Data:
    {state["history"]}

    ANSWER:
    """

    print("\nSummary LLM Prompt:\n", prompt)

    result = llm.generate(prompt)

    return {**state, "final_answer": result}
